<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bnf</string>
	</array>
	<key>name</key>
	<string>GoccBNF</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sdt</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#chars</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(builtin)\b</string>
			<key>name</key>
			<string>storage.type.proto</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\_([A-Za-z][A-Za-z0-9_]*)\b</string>
			<key>name</key>
			<string>variable.other.bnf</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>chars</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.double.bnf</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.bnf</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.bnf</string>
				</dict>
			</array>
		</dict>
		<key>sdt</key>
		<dict>
			<key>begin</key>
			<string>&lt;&lt;</string>
			<key>end</key>
			<string>&gt;&gt;</string>
			<key>name</key>
			<string>keyword.source.bnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#vars</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.bnf</string>
		</dict>
		<key>vars</key>
		<dict>
			<key>match</key>
			<string>\$(\d+)</string>
			<key>name</key>
			<string>variable.other.bnf</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bnf</string>
	<key>uuid</key>
	<string>aa2d0b78-7845-4803-8f3d-72cf584748af</string>
</dict>
</plist>
